# Analysis max_return.csv

In [2]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
max_return_csv = "results/return.csv"

df = pd.read_csv(max_return_csv, sep=";")
try:
    def func(x):
        if type(x) == str:
            return np.array(list(map(float, x.strip('[] ,').split(', '))))
    df["test_return"] = df["test_return"].map(func)
except ValueError as e:
    print(e)
df

,model,env,env_args,seed,test_return
0,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",12,"[1.484375, 1.640625, 1.953125]"
1,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",12,"[1.328125, 1.640625, 1.5625]"
2,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.71875, 0.9375, 2.265625]"
3,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.96875, 2.8125]"
4,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.71875, 1.71875, 2.1875]"
5,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.5625, 1.71875, 2.65625]"
6,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",13,"[1.875, 3.4375, 2.34375]"
7,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",13,"[2.109375, 2.109375, 2.65625]"

In [4]:
df['test_return_mean_run'] = df['test_return'].apply(np.mean)
df['test_return_std_run'] = df['test_return'].apply(np.std)
df

,model,env,env_args,seed,test_return,test_return_mean_run,test_return_std_run
0,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",12,"[1.484375, 1.640625, 1.953125]",1.692708,0.194878
1,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",12,"[1.328125, 1.640625, 1.5625]",1.510417,0.132787
2,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.71875, 0.9375, 2.265625]",1.640625,0.545012
3,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.96875, 2.8125]",2.447917,0.629325
4,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.71875, 1.71875, 2.1875]",1.875000,0.220971
5,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.5625, 1.71875, 2.65625]",1.979167,0.483001
6,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",13,"[1.875, 3.4375, 2.34375]",2.552083,0.654677
7,mappo-gnn_cr0.5,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",13,"[2.109375, 2.109375, 2.65625]",2.291667,0.257799

In [5]:
agg_per_seed_df = df.groupby(["env", "env_args", "model"]).agg(
    count = ("seed", "count"),
	concat = ("test_return_mean_run", lambda x: list(x)),
    test_return_mean = ("test_return_mean_run", "mean"),
    test_return_std  = ("test_return_std_run", "std"),
)
agg_per_seed_df["test_return_tex"] = (
    agg_per_seed_df["test_return_mean"].map("{:.2f}".format)
    + "$\pm$"
    + agg_per_seed_df["test_return_std"].map("{:.2f}".format)
)
agg_per_seed_df

<>:9: SyntaxWarning: invalid escape sequence '\p'
<>:9: SyntaxWarning: invalid escape sequence '\p'
/scratch/users/v/vcuzinrambau/ipykernel_1468272/991803882.py:9: SyntaxWarning: invalid escape sequence '\p'
  + "$\pm$"

                                                                                       count  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5      2
                                                                      mappo-mlp            2
                   {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5      2
                                                                      mappo-mlp            2

                                                                                                                         concat  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5            [1.5104166666666667, 1.640625]
                                                                      mappo-mlp                     [2.4479166666666665, 1.875]
                   {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5  [1.6927083333333333, 2.2916666666666665]
                                                                      mappo-mlp        [1.9791666666666667, 2.5520833333333335]

                                                                                       test_return_mean  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5          1.575521
                                                                      mappo-mlp                2.161458
                   {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5          1.992188
                                                                      mappo-mlp                2.265625

                                                                                       test_return_std  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5         0.291487
                                                                      mappo-mlp               0.288750
                   {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5         0.044492
                                                                      mappo-mlp               0.121394

                                                                                      test_return_tex
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5   1.58$\pm$0.29
                                                                      mappo-mlp         2.16$\pm$0.29
                   {"benchmark_data":true,"dynamic_rescaling":true... mappo-gnn_cr0.5   1.99$\pm$0.04
                                                                      mappo-mlp         2.27$\pm$0.12

In [6]:
test_return_table = agg_per_seed_df.reset_index().pivot(index=["env", "env_args"], columns="model", values=["test_return_mean", "concat", "test_return_tex"])
test_return_table

                                                                      test_return_mean  \
model                                                                  mappo-gnn_cr0.5
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...         1.575521
                   {"benchmark_data":true,"dynamic_rescaling":true...         1.992188

                                                                                 \
model                                                                 mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  2.161458
                   {"benchmark_data":true,"dynamic_rescaling":true...  2.265625

                                                                                                         concat  \
model                                                                                           mappo-gnn_cr0.5
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...            [1.5104166666666667, 1.640625]
                   {"benchmark_data":true,"dynamic_rescaling":true...  [1.6927083333333333, 2.2916666666666665]

                                                                                                                 \
model                                                                                                 mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...               [2.4479166666666665, 1.875]
                   {"benchmark_data":true,"dynamic_rescaling":true...  [1.9791666666666667, 2.5520833333333335]

                                                                      test_return_tex  \
model                                                                 mappo-gnn_cr0.5
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...   1.58$\pm$0.29
                   {"benchmark_data":true,"dynamic_rescaling":true...   1.99$\pm$0.04


model                                                                      mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  2.16$\pm$0.29
                   {"benchmark_data":true,"dynamic_rescaling":true...  2.27$\pm$0.12

In [7]:
best_model = test_return_table["test_return_mean"].idxmax(axis=1)
best_model

env                 env_args
mpe2-simple-tag-v3  {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100}    mappo-mlp
                    {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"RandomTag","render_mode":"rgb_array","time_limit":100}    mappo-mlp
dtype: str

In [8]:
def func(row, best_model):
    best_model_name = best_model.loc[row.name]
    best_model_array = row["concat"].loc[best_model_name]
    print(f"for {row.name} the best model is {best_model_name}")
    row.loc["test_return_tex", best_model_name] += " *"
    for model, concat in row["concat"].items():
        if model != best_model_name:
            res = st.ttest_ind(best_model_array, concat, equal_var=False)
            if res.pvalue > 0.05:
                print(f"{model} is not significatively different")
                row.loc["test_return_tex", model] += " *"
    return row

test_return_table = test_return_table.apply(func, args=(best_model,), axis=1)
test_return_table["test_return_tex"]

for ('mpe2-simple-tag-v3', '{"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100}') the best model is mappo-mlp
mappo-gnn_cr0.5 is not significatively different
for ('mpe2-simple-tag-v3', '{"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"RandomTag","render_mode":"rgb_array","time_limit":100}') the best model is mappo-mlp
mappo-gnn_cr0.5 is not significatively different

model                                                                  mappo-gnn_cr0.5  \
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  1.58$\pm$0.29 *
                   {"benchmark_data":true,"dynamic_rescaling":true...  1.99$\pm$0.04 *

model                                                                        mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  2.16$\pm$0.29 *
                   {"benchmark_data":true,"dynamic_rescaling":true...  2.27$\pm$0.12 *

In [9]:
latex_to_print = test_return_table["test_return_tex"].to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    )
print(latex_to_print)

\begin{tabular}{llll}
\toprule
 & model & mappo-gnn_cr0.5 & mappo-mlp \\
env & env_args &  &  \\
\midrule
\multirow[t]{2}{*}{mpe2-simple-tag-v3} & {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100} & 1.58$\pm$0.29 * & 2.16$\pm$0.29 * \\
 & {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"RandomTag","render_mode":"rgb_array","time_limit":100} & 1.99$\pm$0.04 * & 2.27$\pm$0.12 * \\
\cline{1-4}
\bottomrule
\end{tabular}