# Analysis max_return.csv

In [27]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [28]:
max_return_csv = "results/return.csv"

df = pd.read_csv(max_return_csv, sep=";")
try:
    def func(x):
        if type(x) == str:
            return np.array(list(map(float, x.strip('[] ,').split(', '))))
    df["test_return"] = df["test_return"].map(func)
except ValueError as e:
    print(e)
df

,model,env,env_args,seed,test_return
0,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.09375, 2.03125, 3.125, 6.25, 6.25, 7.5, 5.1..."
1,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.796875, 1.875, 1.875, 3.359375, 3.90625, 4...."
2,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.171875, 1.640625, 1.796875, 1.875, 2.03125,..."
3,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.875, 2.65625, 2.1875, 3.90625, 3.90625, 4.2..."
4,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.953125, 2.03125, 1.953125, 1.40625, 1.79687..."
5,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[2.3958333333333335, 2.0833333333333335, 1.562..."
6,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 2.1875, 1.875, 2.65625, 3.125, 3.75,..."
7,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 1.953125, 2.109375, 2.578125, 3.75, ..."
8,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 1.640625, 1.484375, 2.578125, 2.1093..."
9,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.71875, 1.71875, 2.8125, 1.875, 2.65625, 3.5..."
10,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.25, 1.953125, 1.5625, 3.515625, 3.984375, 2..."
11,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.25, 3.90625, 3.125, 7.03125, 8.28125, 10.15..."
12,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.5, 3.125, 2.96875, 4.84375, 3.82812..."
13,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.109375, 1.640625, 3.203125, 2.5, 1...."
14,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.96875, 2.96875, 4.6875, 3.59375, 3...."
15,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 1.328125, 2.65625, 3.046875, 2.265625..."
16,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.7708333333333333, 1.875, 3.2291666666666665..."
17,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[2.0833333333333335, 3.9583333333333335, 4.375..."

In [29]:
df['test_return_max_run'] = df['test_return'].apply(np.max)
df['test_return_std_run'] = df['test_return'].apply(np.std)
df

,model,env,env_args,seed,test_return,test_return_max_run,test_return_std_run
0,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.09375, 2.03125, 3.125, 6.25, 6.25, 7.5, 5.1...",50.937500,17.321994
1,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.796875, 1.875, 1.875, 3.359375, 3.90625, 4....",10.546875,2.309253
2,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.171875, 1.640625, 1.796875, 1.875, 2.03125,...",16.171875,4.190727
3,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.875, 2.65625, 2.1875, 3.90625, 3.90625, 4.2...",12.500000,2.786232
4,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[1.953125, 2.03125, 1.953125, 1.40625, 1.79687...",25.312500,7.431797
5,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",0,"[2.3958333333333335, 2.0833333333333335, 1.562...",7.604167,1.359625
6,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 2.1875, 1.875, 2.65625, 3.125, 3.75,...",50.937500,17.871907
7,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 1.953125, 2.109375, 2.578125, 3.75, ...",10.781250,2.448910
8,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.40625, 1.640625, 1.484375, 2.578125, 2.1093...",15.312500,4.372196
9,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.71875, 1.71875, 2.8125, 1.875, 2.65625, 3.5...",10.468750,2.747388
10,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.25, 1.953125, 1.5625, 3.515625, 3.984375, 2...",23.671875,7.663333
11,mappo-FO,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.25, 3.90625, 3.125, 7.03125, 8.28125, 10.15...",51.562500,15.522950
12,mappo-rnn,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.5, 3.125, 2.96875, 4.84375, 3.82812...",9.765625,1.652354
13,mappo-gnn_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.109375, 1.640625, 3.203125, 2.5, 1....",17.734375,4.347763
14,mappo-mlp,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 2.96875, 2.96875, 4.6875, 3.59375, 3....",12.343750,2.929458
15,mappo-g-r_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[1.5625, 1.328125, 2.65625, 3.046875, 2.265625...",22.578125,7.010688
16,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",1,"[1.7708333333333333, 1.875, 3.2291666666666665...",8.645833,1.589294
17,mappo-r-g_cr1.0,mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":tru...",2,"[2.0833333333333335, 3.9583333333333335, 4.375...",8.645833,1.413917

In [30]:
agg_per_seed_df = df.groupby(["env", "env_args", "model"]).agg(
    count = ("seed", "count"),
	concat = ("test_return_max_run", lambda x: list(x)),
    test_return_max = ("test_return_max_run", "mean"),
    test_return_std  = ("test_return_max_run", "std"),
)
agg_per_seed_df

agg_per_seed_df["test_return_tex"] = (
    agg_per_seed_df["test_return_max"].map("{:.2f}".format)
    + "$\pm$"
    + agg_per_seed_df["test_return_std"].map("{:.2f}".format)
)
agg_per_seed_df

<>:11: SyntaxWarning: invalid escape sequence '\p'
<>:11: SyntaxWarning: invalid escape sequence '\p'
/scratch/users/v/vcuzinrambau/ipykernel_1263374/4282001630.py:11: SyntaxWarning: invalid escape sequence '\p'
  + "$\pm$"

                                                                                       count  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-FO             3
                                                                      mappo-g-r_cr1.0      3
                                                                      mappo-gnn_cr1.0      3
                                                                      mappo-mlp            3
                                                                      mappo-r-g_cr1.0      3
                                                                      mappo-rnn            3

                                                                                                                                  concat  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-FO                               [50.9375, 50.9375, 51.5625]
                                                                      mappo-g-r_cr1.0                    [25.3125, 23.671875, 22.578125]
                                                                      mappo-gnn_cr1.0                    [16.171875, 15.3125, 17.734375]
                                                                      mappo-mlp                               [12.5, 10.46875, 12.34375]
                                                                      mappo-r-g_cr1.0  [7.604166666666667, 8.645833333333334, 8.64583...
                                                                      mappo-rnn                          [10.546875, 10.78125, 9.765625]

                                                                                       test_return_max  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-FO               51.145833
                                                                      mappo-g-r_cr1.0        23.854167
                                                                      mappo-gnn_cr1.0        16.406250
                                                                      mappo-mlp              11.770833
                                                                      mappo-r-g_cr1.0         8.298611
                                                                      mappo-rnn              10.364583

                                                                                       test_return_std  \
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-FO                0.360844
                                                                      mappo-g-r_cr1.0         1.376272
                                                                      mappo-gnn_cr1.0         1.227831
                                                                      mappo-mlp               1.130340
                                                                      mappo-r-g_cr1.0         0.601407
                                                                      mappo-rnn               0.531786

                                                                                      test_return_tex
env                env_args                                           model
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true... mappo-FO         51.15$\pm$0.36
                                                                      mappo-g-r_cr1.0  23.85$\pm$1.38
                                                                      mappo-gnn_cr1.0  16.41$\pm$1.23
                                                                      mappo-mlp        11.77$\pm$1.13
                                                                      mappo-r-g_cr1.0   8.30$\pm$0.60
                                                                      mappo-rnn        10.36$\pm$0.53

In [31]:
test_return_table = agg_per_seed_df.reset_index().pivot(index=["env", "env_args"], columns="model", values=["test_return_max", "concat", "test_return_tex"])
test_return_table

                                                                      test_return_max  \
model                                                                        mappo-FO
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...       51.145833

                                                                                       \
model                                                                 mappo-g-r_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...       23.854167

                                                                                       \
model                                                                 mappo-gnn_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...        16.40625

                                                                                  \
model                                                                  mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  11.770833

                                                                                       \
model                                                                 mappo-r-g_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...        8.298611

                                                                                  \
model                                                                  mappo-rnn
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  10.364583

                                                                                            concat  \
model                                                                                     mappo-FO
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [50.9375, 50.9375, 51.5625]

                                                                                                        \
model                                                                                  mappo-g-r_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [25.3125, 23.671875, 22.578125]

                                                                                                        \
model                                                                                  mappo-gnn_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [16.171875, 15.3125, 17.734375]

                                                                                                   \
model                                                                                   mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [12.5, 10.46875, 12.34375]

                                                                                                                          \
model                                                                                                    mappo-r-g_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [7.604166666666667, 8.645833333333334, 8.64583...

                                                                                                        \
model                                                                                        mappo-rnn
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  [10.546875, 10.78125, 9.765625]

                                                                      test_return_tex  \
model                                                                        mappo-FO
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  51.15$\pm$0.36

                                                                                       \
model                                                                 mappo-g-r_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  23.85$\pm$1.38

                                                                                       \
model                                                                 mappo-gnn_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  16.41$\pm$1.23

                                                                                       \
model                                                                       mappo-mlp
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  11.77$\pm$1.13

                                                                                       \
model                                                                 mappo-r-g_cr1.0
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...   8.30$\pm$0.60


model                                                                       mappo-rnn
env                env_args
mpe2-simple-tag-v3 {"benchmark_data":true,"dynamic_rescaling":true...  10.36$\pm$0.53

In [32]:
best_model = test_return_table["test_return_max"].idxmax(axis=1)
best_model

env                 env_args
mpe2-simple-tag-v3  {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100}    mappo-FO
dtype: str

In [33]:
def func(row, best_model):
    best_model_name = best_model.loc[row.name]
    best_model_array = row["concat"].loc[best_model_name]
    print(f"for {row.name} the best model is {best_model_name}")
    row.loc["test_return_tex", best_model_name] += " *"
    for model, concat in row["concat"].items():
        if model != best_model_name:
            res = st.ttest_ind(best_model_array, concat, equal_var=False)
            if res.pvalue > 0.05:
                print(f"{model} is not significatively different")
                row.loc["test_return_tex", model] += " *"
    return row

test_return_table = test_return_table.apply(func, args=(best_model,), axis=1)
test_return_table["test_return_tex"]

for ('mpe2-simple-tag-v3', '{"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100}') the best model is mappo-FO

,model,mappo-FO,mappo-g-r_cr1.0,mappo-gnn_cr1.0,mappo-mlp,mappo-r-g_cr1.0,mappo-rnn
env,env_args,,,,,,
mpe2-simple-tag-v3,"{""benchmark_data"":true,""dynamic_rescaling"":true,""key"":""mpe2-simple-tag-v3"",""max_cycles"":50,""num_adversaries"":6,""num_good"":2,""num_obstacles"":0,""observation_range"":0.25,""pretrained_wrapper"":""FrozenTag"",""render_mode"":""rgb_array"",""time_limit"":100}",51.15$\pm$0.36 *,23.85$\pm$1.38,16.41$\pm$1.23,11.77$\pm$1.13,8.30$\pm$0.60,10.36$\pm$0.53

In [34]:
latex_to_print = test_return_table["test_return_tex"].to_latex(
        index=True, formatters={"name": str.upper}, float_format="{:.1f}".format
    )
print(latex_to_print)

\begin{tabular}{llllllll}
\toprule
 & model & mappo-FO & mappo-g-r_cr1.0 & mappo-gnn_cr1.0 & mappo-mlp & mappo-r-g_cr1.0 & mappo-rnn \\
env & env_args &  &  &  &  &  &  \\
\midrule
mpe2-simple-tag-v3 & {"benchmark_data":true,"dynamic_rescaling":true,"key":"mpe2-simple-tag-v3","max_cycles":50,"num_adversaries":6,"num_good":2,"num_obstacles":0,"observation_range":0.25,"pretrained_wrapper":"FrozenTag","render_mode":"rgb_array","time_limit":100} & 51.15$\pm$0.36 * & 23.85$\pm$1.38 & 16.41$\pm$1.23 & 11.77$\pm$1.13 & 8.30$\pm$0.60 & 10.36$\pm$0.53 \\
\cline{1-8}
\bottomrule
\end{tabular}